name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, xml, ctype, curl, fileinfo, filter, hash, openssl, pcre, pdo, session, tokenizer, zip
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Install NPM dependencies
      run: npm install

    - name: Install Composer dependencies
      run: composer install

    - name: Generate key
      run: php artisan key:generate

    - name: Set permissions
      run: sudo chmod -R 777 storage bootstrap/cache

    - name: Create database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run migrations
      run: php artisan migrate

    - name: Execute tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
